language: generic
git:
  depth: false
branches:
  only:
    - master
    - develop
    - /^feature.*/
env:
  global:
    - VERSION=${TRAVIS_COMMIT:0:8}
    - BRANCH=$TRAVIS_BRANCH
    - PROJECT_NAME=opensiddur-client
    - INSTANCE_BASE=${PROJECT_NAME}-proxy-${BRANCH//\//-}
    - INSTANCE_NAME=${INSTANCE_BASE}-${VERSION}
    - ZONE=us-west2-a
    - MACHINE_TYPE=g1-small
    - IMAGE=ubuntu-2004-focal-v20200529
    - IMAGE_PROJECT=ubuntu-os-cloud
    - BOOT_DISK_SIZE_GB=10
    - SERVICE_ACCOUNT=opensiddur-deploy-1@opensiddur-client.iam.gserviceaccount.com

before_install:
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
  - git lfs pull
  - export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
  - echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee
    -a /etc/apt/sources.list.d/google-cloud-sdk.list
  - curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add
  - sudo apt-get update -y
  - sudo apt-get install -y google-cloud-sdk
  - openssl aes-256-cbc -K $encrypted_179021bd20db_key -iv $encrypted_179021bd20db_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
  - tar zxvf credentials.tar.gz
  - gcloud auth activate-service-account --key-file=client-secret.json
  - gcloud config set project ${PROJECT_NAME}
  - ssh-keygen -q -N "" -f ~/.ssh/google_compute_engine

script:
  - |
    gcloud compute \
      --project=${PROJECT_NAME} instances create ${INSTANCE_NAME} \
      --zone=${ZONE} \
      --machine-type=${MACHINE_TYPE} \
      --network=default \
      --network-tier=PREMIUM \
      --maintenance-policy=MIGRATE \
      --scopes=https://www.googleapis.com/auth/cloud-platform \
      --tags=http-server,https-server \
      --image=${IMAGE} \
      --image-project=${IMAGE_PROJECT} \
      --boot-disk-size=${BOOT_DISK_SIZE_GB}GB \
      --boot-disk-type=pd-standard \
      --boot-disk-device-name=${INSTANCE_NAME} \
      --service-account=${SERVICE_ACCOUNT} \
      --metadata-from-file startup-script=setup/gcloud-startup-script.sh \
      --metadata BRANCH=${BRANCH},enable-oslogin=true

